name: master-cd

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: github.repository == 'crustio/crust-home'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build bundle
        run: yarn generate

      - name: Build and push docker
        run: |
          docker build -t crustio/crust-web:latest .
          docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push crustio/crust-web:latest
      - name: Upgrade home web
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull crustio/crust-web:latest
            cd /opt/compose
            docker tag crustio/crust-web:latest compose_crust-web
            docker-compose up -d crust-web
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
